# add-key.yml
- name: Add Ansible controller public key to the user's authorized_keys
  hosts: raspberrypi
  become: true
  tasks:
    - name: Ensure .ssh directory exists for the user
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0700

    - name: Copy Ansible controller public key to authorized_keys
      copy:
        src: /home/pi/.ssh/id_rsa.pub
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600
    
    - name: Ensure the sudoers file includes passwordless sudo for the user
      copy:
        dest: "/etc/sudoers.d/{{ ansible_user }}"
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: '0440'